# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4540ab7ab2d61a047ca63a47485fec6d"
name = "edit-order-test"
handle = "edit-order-test"
application_url = "https://portion-labeled-indices-myers.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demo1-demo.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,read_script_tags,read_themes,write_customers,write_order_edits,write_orders,write_script_tags"

[auth]
redirect_urls = [
  "https://portion-labeled-indices-myers.trycloudflare.com/auth/callback",
  "https://portion-labeled-indices-myers.trycloudflare.com/auth/shopify/callback",
  "https://portion-labeled-indices-myers.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
